title: Teste de Software
author: Jackson Antonio do Prado Lima
copyright: "2025"

# Configurações do repositório para adicionar links "Edit this page", etc.
repository:
  url: https://github.com/jacksonpradolima/teste-software
  path_to_book: / 
  branch: main 

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid

only_build_toc_files        : true